title: Zirui Li
position: Ph.D. Candidate
affiliation: Beijing Institute of Technology/ TU Dresden
email: z.li@bit.edu.cn / zirui.li@tu-dresden.de
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=nCHChhsAAAAJ&hl=zh-CN
github_link: https://github.com/lzrbit
linkedin: https://www.linkedin.com/in/zirui-li-25a63a200/
avatar: ./assets/img/self-pic.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Update Dec. 2022.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
